@startuml
actor ユーザー as user
participant ブラウザ as browser
participant Next.js as api
participant PostgreSQL as db

== 動物をお気に入り登録/解除する ==
user -> browser: 動物詳細画面を表示
user -> browser: お気に入りボタンを押下
browser -> api: お気に入り登録APIにアクセス (POST)
api -> db: お気に入り情報をDBに登録
db -> api: 登録結果を返す
api -> browser: 登録結果を返す
browser -> user: 処理完了トーストを表示

@enduml
