@startuml
actor ユーザー as user
participant ブラウザ as browser
participant Next.js as api
participant "Supabase Storage" as storage
participant PostgreSQL as db

==  動物を登録する（ファイルアップロードを含まない） ==
user -> browser: 動物情報を入力
user -> browser: 登録ボタンを押下
browser -> api: 動物情報をDBに登録リクエスト (POST)
api -> db: 動物情報をDBに登録
db -> api: 登録結果を返す
api -> browser: 登録完了結果を返す
browser -> user: 処理完了トーストを表示

@enduml
